language: dart

dart:
  - dev
  - 2.0.0

dart_task:
  - test: --platform vm
  # No parallelism on Firefox (-j 1)
  # Causes flakiness â€“ need to investigate
  - test: --platform firefox -j 1
  - dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
