name: http
version: 0.12.0+2
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  async: ">=1.10.0 <3.0.0"
  http_parser: ">=0.0.1 <4.0.0"
  path: ">=0.9.0 <2.0.0"
  pedantic: "^1.0.0"

dev_dependencies:
  test: ^1.3.0
