name: http
version: 0.12.1
homepage: https://github.com/dart-lang/http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http_parser: ">=0.0.1 <4.0.0"
  path: ">=0.9.0 <2.0.0"
  pedantic: "^1.0.0"

dev_dependencies:
  test: ^1.3.0
