name: http
version: 0.13.0-nullsafety.0
homepage: https://github.com/dart-lang/http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http_parser: ^4.0.0-nullsafety
  meta: ^1.3.0-nullsafety.3
  path: ^1.8.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety.4

dependency_overrides:
  http_parser: ^4.0.0-nullsafety
  # Because pkg:test does not support pkg:http ^0.13.0
  test: ^1.16.0-nullsafety.5
