name: cronet_http_example
description: Demonstrates how to use the cronet_http plugin.

publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  cronet_http:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  http_image_provider: ^0.0.2
  provider: ^6.1.1

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_client_conformance_tests:
    path: ../../http_client_conformance_tests/
  integration_test:
    sdk: flutter
  test: ^1.23.1

flutter:
  uses-material-design: true
