name: cupertino_http
version: 1.4.0-wip
publish_to: none  # Do not merge with this here!

description: >-
  A macOS/iOS Flutter plugin that provides access to the Foundation URL
  Loading System.
repository: https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http
publish_to: none
environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'  # If changed, update test matrix.

dependencies:
  async: ^2.5.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.0
<<<<<<< HEAD
  http_profile:
    path: ../http_profile
=======
  web_socket:
    path: ../web_socket
>>>>>>> upstream/master

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  ffigen: ^9.0.1

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
