name: cupertino_http
version: 1.4.0
description: >-
  A macOS/iOS Flutter plugin that provides access to the Foundation URL
  Loading System.
repository: https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'  # If changed, update test matrix.

dependencies:
  async: ^2.5.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  ffigen: ^9.0.1

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
