name: cupertino_http
description: >
  A macOS/iOS Flutter plugin that provides access to the Foundation URL
  Loading System.
version: 0.0.4
repository: https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  ffi: ^1.2.1
  flutter:
    sdk: flutter
  http: ^0.13.4
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.0.0
  lints: ^1.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
