name: cupertino_http
version: 2.0.2-wip
description: >-
  A macOS/iOS Flutter plugin that provides access to the Foundation URL
  Loading System.
repository: https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http
issue_tracker: https://github.com/dart-lang/http/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Acupertino_http

environment:
  sdk: ^3.4.0
  flutter: '>=3.24.0' # If changed, update test matrix.

dependencies:
  async: ^2.5.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_profile: ^0.1.0
  objective_c: ^4.0.0
  web_socket: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  ffigen: ^16.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
