name: web_socket_conformance_tests
description: >-
  A library that tests whether implementations of `package:web_socket`'s
  `WebSocket` class behave as expected.
repository: https://github.com/dart-lang/http/tree/master/pkgs/web_socket_conformance_tests

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.11.0
  crypto: ^3.0.3
  dart_style: ^2.3.4
  stream_channel: ^2.1.2
  test: ^1.24.0
  web_socket: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
