name: cronet_http
version: 1.3.2
description: >-
  An Android Flutter plugin that provides access to the Cronet HTTP client.
repository: https://github.com/dart-lang/http/tree/master/pkgs/cronet_http

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_profile: ^0.1.0
  jni: ^0.10.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  jnigen: ^0.10.0
  xml: ^6.1.0
  yaml_edit: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
