name: cronet_http
description: >
  An Android Flutter plugin that provides access to the Cronet HTTP client.
version: 0.2.0
repository: https://github.com/dart-lang/http/tree/master/pkgs/cronet_http

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  pigeon: ^3.2.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.cronet_http
        pluginClass: CronetHttpPlugin
