name: http_client_conformance_tests
description: >-
  A library that tests whether implementations of package:http's `Client` class
  behave as expected.
publish_to: none
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_client_conformance_tests

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.8.2
  dart_style: ^2.2.3
  http: ^0.13.4
  stream_channel: ^2.1.1
  test: ^1.21.2

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
