name: http_client_conformance_tests
description: >-
  A library that tests whether implementations of package:http's `Client` class
  behave as expected.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_client_conformance_tests

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.8.2
  http: ^1.2.0
  stream_channel: ^2.1.1
  test: ^1.21.2

dev_dependencies:
  dart_style: ^2.3.7
  dart_flutter_team_lints: ^3.0.0
