name: websocket
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  web_socket_conformance_tests:
    path: ../web_socket_conformance_tests
dependencies:
  web: ^0.4.2
