name: http_profile
description: >-
  A library used by HTTP client authors to integrate with the DevTools Network
  tab.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_profile

publish_to: none

environment:
  # TODO(derekxu16): Change the following constraint to ^3.4.0 before publishing this package.
  sdk: ^3.4.0-154.0.dev

dependencies:
  test: ^1.24.9

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
