name: http_profile
description: >-
  A library used by HTTP client authors to integrate with the DevTools Network
  View.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_profile
version: 0.1.0

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.9
