name: flutter_http_example
version: 1.0.0
description: Demonstrates how to use package:http in a Flutter app.

publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cronet_http: ^1.0.0
  cupertino_http: ^1.2.0
  cupertino_icons: ^1.0.2
  fetch_client: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  http_image_provider: ^0.0.3
  provider: ^6.0.5

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.21.1

flutter:
  uses-material-design: true
