name: http_parser
version: 3.1.4
description: >-
  A platform-independent package for parsing and serializing HTTP formats.
homepage: https://github.com/dart-lang/http_parser

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  collection: '>=0.9.1 <2.0.0'
  source_span: ^1.0.0
  string_scanner: '>=0.0.0 <2.0.0'
  typed_data: ^1.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
