name: http_parser
version: 4.1.2
description: >-
  A platform-independent package for parsing and serializing HTTP formats.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_parser

environment:
  sdk: ^3.4.0

dependencies:
  collection: ^1.19.0
  source_span: ^1.8.0
  string_scanner: ^1.1.0
  typed_data: ^1.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
