name: http
version: 1.6.1-wip
description: A composable, multi-platform, Future-based API for HTTP requests.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http

topics:
  - http
  - network
  - protocols

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.5.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  web: ">=0.5.0 <2.0.0"

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  fake_async: ^1.2.0
  http_client_conformance_tests:
    path: ../http_client_conformance_tests/
  shelf: ^1.1.0
  stream_channel: ^2.1.1
  test: ^1.21.2
