name: cupertino_http_example
description: Demonstrates how to use the cupertino_http plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'

dependencies:
  cupertino_http:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  http_image_provider: ^1.0.0
  provider: ^6.1.1

dev_dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  dart_flutter_team_lints: ^3.0.0
  ffi: ^2.1.4
  flutter_test:
    sdk: flutter
  http_client_conformance_tests:
    path: ../../http_client_conformance_tests/
  http_profile: ^0.1.0
  integration_test:
    sdk: flutter
  objective_c: ^9.1.0
  test: ^1.21.1
  web_socket: '^1.0.0'
  web_socket_conformance_tests:
    path: ../../web_socket_conformance_tests/

flutter:
  uses-material-design: true

# Use the path version of `package:http` so that the behavior matches the
# expectations in http_client_conformance_tests.
dependency_overrides:
  http:
    path: ../../http/
