name: cupertino_http_example
description: Demonstrates how to use the cupertino_http plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  cupertino_http:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  http_image_provider: ^0.0.3
  provider: ^6.1.1

dev_dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  dart_flutter_team_lints: ^3.0.0
  ffi: ^2.0.1
  flutter_test:
    sdk: flutter
  http_client_conformance_tests:
    path: ../../http_client_conformance_tests/
  http_profile: ^0.1.0
  integration_test:
    sdk: flutter
  test: ^1.21.1
  web_socket_conformance_tests:
    path: ../../web_socket_conformance_tests/

flutter:
  uses-material-design: true
