name: java_http
version: 0.0.1
description: >-
  A Dart package for making HTTP requests using java.net.HttpURLConnection.
repository: https://github.com/dart-lang/http/tree/master/pkgs/java_http

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.11.0
  http: '>=0.13.4 <2.0.0'
  jni: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http_client_conformance_tests:
    path: ../http_client_conformance_tests/
  jnigen: ^0.5.0
  test: ^1.21.0
