name: java_http
description: A Dart package for making HTTP requests using java.net.HttpURLConnection.
version: 0.0.1
repository: https://github.com/dart-lang/http/tree/master/pkgs/java_http
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  http: '>=0.13.4 <2.0.0'
  jni: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  jnigen: ^0.5.0
  lints: ^2.0.0
  test: ^1.21.0
