language: dart

dart:
  - 2.1.0
  - dev

dart_task:
  - test
  - dartanalyzer

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
