name: web_socket_channel
version: 3.0.4-wip
description: >-
  A WebSocket API that enables cross-platform communication via StreamChannel.
repository: https://github.com/dart-lang/http/tree/master/pkgs/web_socket_channel

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.5.0
  crypto: ^3.0.0
  stream_channel: ^2.1.0
  web: '>=0.5.0 <2.0.0'
  web_socket: '>=0.1.5 <2.0.0'

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.2

topics:
 - web
 - http
