name: web_socket_channel
version: 1.0.4
description: StreamChannel wrappers for WebSockets.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  async: '^1.3.0'
  crypto: '>=0.9.2 <3.0.0'
  stream_channel: '^1.2.0'

dev_dependencies:
  test: '^0.12.0'
