name: http2
version: 2.3.1
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http/tree/master/pkgs/http2
issue_tracker: https://github.com/dart-lang/http/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ahttp2

topics:
 - http
 - network
 - protocols

environment:
  sdk: ^3.2.0

dev_dependencies:
  build_runner: ^2.3.0
  dart_flutter_team_lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.4
