name: http2
version: 2.3.1-wip
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: ^3.2.0

dev_dependencies:
  build_runner: ^2.3.0
  dart_flutter_team_lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.4
