name: http2
version: 0.1.9
description: A HTTP/2 implementation in Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/http2

environment:
  sdk: '>=2.0.0-dev.56.0 <3.0.0'

dev_dependencies:
  mockito: ^3.0.0-beta+2
  test: ^1.2.0
