name: package:cronet_http CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/cronet.yaml'
      - 'pkgs/cronet_http/**'
      - 'pkgs/http_client_conformance_tests/**'
  pull_request:
    paths:
      - '.github/workflows/cronet.yaml'
      - 'pkgs/cronet_http/**'
      - 'pkgs/http_client_conformance_tests/**'
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  verify:
    name: Format & Analyze & Test
    runs-on: macos-latest
    strategy:
      matrix:
        package: ['cronet_http', 'cronet_http_embedded']
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          channel: 'stable'
      - name: Make cronet_http_embedded copy
        if: ${{ matrix.package == 'cronet_http_embedded' }}
        run: |
          mv pkgs/cronet_http pkgs/cronet_http_embedded
          cd pkgs/cronet_http_embedded
          flutter pub get && dart tool/prepare_for_embedded.dart
      - id: install
        name: Install dependencies
        working-directory: 'pkgs/${{ matrix.package }}'
        run: flutter pub get
      - name: Check formatting
        if: always() && steps.install.outcome == 'success'
        working-directory: 'pkgs/${{ matrix.package }}'
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        if: always() && steps.install.outcome == 'success'
        working-directory: 'pkgs/${{ matrix.package }}'
        run: flutter analyze --fatal-infos
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2
        if: always() && steps.install.outcome == 'success'
        with:
          # api-level/minSdkVersion should be help in sync in:
          # - .github/workflows/cronet.yml
          # - pkgs/cronet_http/android/build.gradle
          # - pkgs/cronet_http/example/android/app/build.gradle
          api-level: 21
          arch: x86_64
          target: ${{ matrix.package == 'cronet_http_embedded' && 'default' || 'google_apis' }}
          profile: pixel
          script: |
            cd pkgs/${{ matrix.package }}/example && pwd && ls -al
            flutter pub get
            flutter test --timeout=1200s integration_test/
