# Created with package:mono_repo v6.5.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.5.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Dart 2.19.0; PKGS: pkgs/http, pkgs/http_client_conformance_tests; `dart analyze --fatal-infos`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http-pkgs/http_client_conformance_tests;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http-pkgs/http_client_conformance_tests
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: "2.19.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart analyze --fatal-infos"
        run: dart analyze --fatal-infos
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
      - id: pkgs_http_client_conformance_tests_pub_upgrade
        name: pkgs/http_client_conformance_tests; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
      - name: "pkgs/http_client_conformance_tests; dart analyze --fatal-infos"
        run: dart analyze --fatal-infos
        if: "always() && steps.pkgs_http_client_conformance_tests_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
  job_003:
    name: "analyze_and_format; Dart dev; PKGS: pkgs/http, pkgs/http_client_conformance_tests; `dart analyze --fatal-infos`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http-pkgs/http_client_conformance_tests;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http-pkgs/http_client_conformance_tests
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart analyze --fatal-infos"
        run: dart analyze --fatal-infos
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
      - id: pkgs_http_client_conformance_tests_pub_upgrade
        name: pkgs/http_client_conformance_tests; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
      - name: "pkgs/http_client_conformance_tests; dart analyze --fatal-infos"
        run: dart analyze --fatal-infos
        if: "always() && steps.pkgs_http_client_conformance_tests_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
  job_004:
    name: "analyze_and_format; Dart dev; PKGS: pkgs/http, pkgs/http_client_conformance_tests; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http-pkgs/http_client_conformance_tests;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http-pkgs/http_client_conformance_tests
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
      - id: pkgs_http_client_conformance_tests_pub_upgrade
        name: pkgs/http_client_conformance_tests; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
      - name: "pkgs/http_client_conformance_tests; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pkgs_http_client_conformance_tests_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http_client_conformance_tests
  job_005:
    name: "unit_test; Dart 2.19.0; PKG: pkgs/http; `dart run --define=no_default_http_client=true test/no_default_http_client_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http;commands:command"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: "2.19.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart run --define=no_default_http_client=true test/no_default_http_client_test.dart"
        run: "dart run --define=no_default_http_client=true test/no_default_http_client_test.dart"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_006:
    name: "unit_test; Dart 2.19.0; PKG: pkgs/http; `dart test --platform chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: "2.19.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart test --platform chrome"
        run: dart test --platform chrome
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_007:
    name: "unit_test; Dart 2.19.0; PKG: pkgs/http; `dart test --platform vm`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.19.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: "2.19.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart test --platform vm"
        run: dart test --platform vm
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_008:
    name: "unit_test; Dart dev; PKG: pkgs/http; `dart run --define=no_default_http_client=true test/no_default_http_client_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:command"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart run --define=no_default_http_client=true test/no_default_http_client_test.dart"
        run: "dart run --define=no_default_http_client=true test/no_default_http_client_test.dart"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_009:
    name: "unit_test; Dart dev; PKG: pkgs/http; `dart test --platform chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart test --platform chrome"
        run: dart test --platform chrome
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_010:
    name: "unit_test; Dart dev; PKG: pkgs/http; `dart test --platform vm`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
      - name: "pkgs/http; dart test --platform vm"
        run: dart test --platform vm
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
