# Created with package:mono_repo v6.2.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: "analyze_and_format; Dart 2.14.0; `dart analyze --fatal-infos`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart analyze --fatal-infos"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart analyze --fatal-infos
  job_002:
    name: "analyze_and_format; Dart dev; `dart analyze --fatal-infos`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart analyze --fatal-infos"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart analyze --fatal-infos
  job_003:
    name: "analyze_and_format; Dart dev; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: "dart format --output=none --set-exit-if-changed ."
  job_004:
    name: "unit_test; Dart 2.14.0; `dart test --platform chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart test --platform chrome"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart test --platform chrome
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; Dart 2.14.0; `dart test --platform vm`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart test --platform vm"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart test --platform vm
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; Dart dev; `dart test --platform chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart test --platform chrome"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart test --platform chrome
    needs:
      - job_001
      - job_002
      - job_003
  job_007:
    name: "unit_test; Dart dev; `dart test --platform vm`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/http
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: pkgs_http_pub_upgrade
        name: pkgs/http; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart pub upgrade
      - name: "pkgs/http; dart test --platform vm"
        if: "always() && steps.pkgs_http_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/http
        run: dart test --platform vm
    needs:
      - job_001
      - job_002
      - job_003
