# A CI configuration to auto-publish pub packages.

name: Publish Flutter Packages

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ '[A-z]+-v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      use-flutter: true
      ignore-packages: |
        pkgs/http/**
        pkgs/http_profile/**
        pkgs/web_socket/**
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
