# A CI configuration to auto-publish pub packages.

name: Publish Dart Packages

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ '[A-z]+-v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      ignore-packages:
      - pkgs/cupertino_http/
      - pkgs/cronet_http/
      - pkgs/ok_http/
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
